name: maid_ai_reader
description: Mobile AI Document-assistant - A smart document reader with AI capabilities
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  audioplayers: ^6.1.0
  cached_network_image: ^3.4.1
  connectivity_plus: ^6.1.0
  crypto: ^3.0.5
  cupertino_icons: ^1.0.6
  dio: ^5.4.0
  equatable: ^2.0.5
  file_picker: ^10.3.10
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_animate: ^4.5.0
  flutter_bloc: ^9.1.1
  flutter_colorpicker: ^1.1.0
  flutter_tts: ^4.2.0
  # font_awesome: ^5.10.1
  get_it: ^9.2.0
  glassmorphism: ^3.0.0
  google_generative_ai: ^0.4.6
  google_ml_kit: ^0.18.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^1.1.2
  intl: ^0.20.2
  local_auth: ^2.3.0
  package_info_plus: ^8.1.0
  path_provider: ^2.1.1
  pdf: ^3.11.1
  permission_handler: ^12.0.1
  printing: ^5.14.2
  record: ^5.1.2
  share_plus: ^10.1.1
  shared_preferences: ^2.2.2
  shimmer: ^3.0.0
  speech_to_text: ^7.0.0
  sqflite: ^2.3.3+1
  syncfusion_flutter_pdf: ^32.1.25
  syncfusion_flutter_pdfviewer: ^32.1.25
  syncfusion_flutter_signaturepad: ^32.1.25
  url_launcher: ^6.3.1
  uuid: ^4.2.2
  flutter_secure_storage: ^9.2.2
  google_mobile_ads: ^5.0.0

dev_dependencies:
  build_runner: ^2.4.7
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  mockito: ^5.4.4

dependency_overrides:
  record_linux: ^1.0.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
